trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'the_count_bot'
    runOptions: 'inline'
    inline: |
      cd ~/bot-repo;
      git fetch;
      git checkout master 2>&1;
      git reset origin/master --hard;
      docker build -t the_count_bot_release_image .;
      docker stop the_count_bot_release_container 2>&1;
      docker rm the_count_bot_release_container 2>&1;
      docker run -d --name  the_count_bot_release_container the_count_bot_release_image:latest;