trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'the_count_bot'
    runOptions: 'inline'
    inline: |
      ls -al;
      cd ~/bot-repo;
      ls -al;
      git fetch;
      git checkout master;
      git reset origin/master --hard;
      docker build -t the_count_bot_release_image .;
      docker stop the_count_bot_release_container;
      docker run -d --name  the_count_bot_release_container the_count_bot_release_image:latest;