// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheCountBot.Data;

namespace TheCountBot.Data.Migrations
{
    [DbContext(typeof(NumberStoreContext))]
    [Migration("20181001222650_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheCountBot.Data.Models.MessageEntry", b =>
                {
                    b.Property<int>("MessageEntryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Correct");

                    b.Property<int>("Number");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("Username")
                        .HasMaxLength(64);

                    b.HasKey("MessageEntryId");

                    b.ToTable("MessageEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
