// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TheCountBot.Application.Clients.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AllUserStatisticsResponse
    {
        /// <summary>
        /// Initializes a new instance of the AllUserStatisticsResponse class.
        /// </summary>
        public AllUserStatisticsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AllUserStatisticsResponse class.
        /// </summary>
        public AllUserStatisticsResponse(IList<UserStatistics> usersStatistics = default(IList<UserStatistics>))
        {
            UsersStatistics = usersStatistics;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usersStatistics")]
        public IList<UserStatistics> UsersStatistics { get; set; }

    }
}
