// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TheCountBot.Application.Clients.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NewMessageResponse
    {
        /// <summary>
        /// Initializes a new instance of the NewMessageResponse class.
        /// </summary>
        public NewMessageResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NewMessageResponse class.
        /// </summary>
        public NewMessageResponse(string userName = default(string), int? number = default(int?), bool? isCorrect = default(bool?), bool? isPalindrome = default(bool?), bool? isAllSameDigits = default(bool?), bool? isPowerOf10 = default(bool?))
        {
            UserName = userName;
            Number = number;
            IsCorrect = isCorrect;
            IsPalindrome = isPalindrome;
            IsAllSameDigits = isAllSameDigits;
            IsPowerOf10 = isPowerOf10;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public int? Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isCorrect")]
        public bool? IsCorrect { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isPalindrome")]
        public bool? IsPalindrome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isAllSameDigits")]
        public bool? IsAllSameDigits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isPowerOf10")]
        public bool? IsPowerOf10 { get; set; }

    }
}
