// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TheCountBot.Application.Clients.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SingleUserStatisticsResponse
    {
        /// <summary>
        /// Initializes a new instance of the SingleUserStatisticsResponse
        /// class.
        /// </summary>
        public SingleUserStatisticsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SingleUserStatisticsResponse
        /// class.
        /// </summary>
        public SingleUserStatisticsResponse(UserStatistics userStatistics = default(UserStatistics))
        {
            UserStatistics = userStatistics;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userStatistics")]
        public UserStatistics UserStatistics { get; set; }

    }
}
